source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-logger'
gem 'sinatra-contrib'
gem 'json'
gem 'dotenv'
gem 'openssl'
gem 'curb'
gem 'icalendar'
gem 'date'
gem 'activesupport' 
gem 'mysql2' 
gem 'sequel' 
gem 'net-ping' 
gem 'base64' 
